import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'
import { prisma } from '../lib/prisma'
import { getUsers } from "./Components/UNUSEDgetServerSideProps";
import { useRouter } from 'next/router'
import { GetServerSideProps } from 'next';

interface FormData {
  name: string
  password: string
  id: string
}

// Array interface
interface User {
  users: {
    id: string
    name: string
    password: string
    email: string
  }[]
}

// Load users from getServerSideProps server side rendering
const Home: NextPage<User> = ({ users }) => {
  const [form, setForm] = useState<FormData>({name: '', password: '', id: ''})
  const [newUser, setNewUser] = useState<Boolean>(true)
  const router = useRouter()

  const refreshData = () => {
    router.replace(router.asPath)
  }

  async function handleSubmit(data: FormData) {
    // console.log(data)
    // console.log(newUser)

    try {
      if (newUser) {
        // Check input is not blank
        if (data.name) {
          // CREATE
          fetch('api/create', {
            body: JSON.stringify(data),
            headers: {
              'Content-Type': 'application/json'
            },
            method: 'POST'
          }).then(() => {
            setForm({name: '', password: '', id: ''})
            refreshData()
          })
        }
        else {
          alert("Name can not be blank")
        }
      }
      else {
        // UPDATE
          fetch(`api/user/${data.id}`, {
            body: JSON.stringify(data),
            headers: {
              'Content-Type': 'application/json',
            },
            method: 'PUT'
          }).then(() => {
            setForm({name: '', password: '', id: ''})
            setNewUser(true)
            refreshData()
          })
      }
    } catch (error) {
      console.log(error)
    }
  }

  async function updateUser(name: string, password: string, id: string) {
    //console.log(name, password, id)
    setForm({name, password, id})
    setNewUser(false)
  }

  async function deleteUser(id: string) {
    try {
      fetch(`api/user/${id}`, {
        headers: {
          'Content-Type': 'application/json',
        },
        method: 'DELETE'
      }).then(() => {
        refreshData()
      })
    } catch (error) {
      console.log(error)
    }    
  }

  function handleCancel() {
    setForm({name: '', password: '', id: ''})
    setNewUser(true)
  }

  return (
    <>
      <Head>
        <title>users</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <h1 className="m-4 text-2xl font-bold text-center">Users</h1>
      <form className="w-auto min-w-[25%] max-w-min mx-auto space-y-6 flex flex-col items-stretch" 
        onSubmit={e => {
          e.preventDefault()
          handleSubmit(form)
      }}>
        <input type="text" 
          placeholder="Name" 
          value={form.name} 
          onChange={e => setForm({...form, name: e.target.value})}
          className="p-1 border-2 border-gray-600 rounded"
        />
        <textarea placeholder="Password" 
          value={form.password} 
          onChange={e => setForm({...form, password: e.target.value})} 
          className="p-1 border-2 border-gray-600 rounded"
        />
        {newUser ? (
          <button type="submit" className="p-1 text-white bg-blue-500 rounded">Add +</button>
        ) : (
          <>
            <button type="submit" className="p-1 text-white bg-blue-500 rounded">Update</button>
            <button onClick={handleCancel} className="p-1 text-white bg-red-500 rounded">Cancel</button>
          </>
        )}
      </form>

      <div className="w-auto min-w-[25%] max-w-min mt-10 mx-auto space-y-6 flex flex-col items-stretch">
        <h2 className="mt-4 text-xl font-bold text-center">Saved Users</h2>
        <ul>
          {users.map(user => (
            <li key={user.id} className="p-2 border-b border-gray-600">
              <div className="flex jusify-between">
                <div className="flex-1">
                  <h3 className="font-bold">{user.name}</h3>
                  <p className="text-sm">{user.password}</p>
                </div>
                <button onClick={() => updateUser(user.name,user.password,user.id)} className="px-3 text-white bg-blue-500 rounded">Edit</button>
                <button onClick={() => deleteUser(user.id)} className="px-3 text-white bg-red-500 rounded">X</button>
              </div>
            </li>
          ))}
        </ul>
      </div>
    </>
  )
}
export const getServerSideProps: GetServerSideProps = async () => {
  // READ all notes from DB
  const users = await prisma?.user.findMany({
    select: {
      id: true,
      name: true,
      password: true,
    },
  });
  console.log(users)
  return {
    props: {
      users,
    },
  };
}

